// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"IgnisMainMenuManager","status":true,"description":"Ignis Main Menu Manager version: 1.0.0","parameters":{"menuOptions":""}}
];
